services:

  # --- FTP Server (Input Layer) ---
  ftp-server:
    image: stilliard/pure-ftpd
    container_name: ftp-server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - PUBLICHOST=ftp-server
      - FTP_USER_NAME=testuser
      - FTP_USER_PASS=testpass
      - FTP_USER_HOME=/home/testuser
    volumes:
      - ./ftp-data:/home/testuser

  # --- Data Sources (Upload via FTP) ---
  msc:
    build: ./msc-service
    depends_on:
      - ftp-server
    environment:
      - FTP_HOST=ftp-server
      - FTP_USER=testuser
      - FTP_PASS=testpass

  smsc:
    build: ./smsc-service
    depends_on:
      - ftp-server
    environment:
      - FTP_HOST=ftp-server
      - FTP_USER=testuser
      - FTP_PASS=testpass

  pgw:
    build: ./pgw-service
    depends_on:
      - ftp-server
    environment:
      - FTP_HOST=ftp-server
      - FTP_USER=testuser
      - FTP_PASS=testpass

  # --- Mediation (Core) ---
  mediation:
    build: ./mediation-service
    depends_on:
      - ftp-server
      - billing
      - fraud
    environment:
      - FTP_HOST=ftp-server
      - FTP_USER=testuser
      - FTP_PASS=testpass
      - BILLING_URL=http://billing:8080/upload
      - FRAUD_URL=http://fraud:8080/upload


  # --- Downstream Systems (HTTP) ---
  billing:
    build: ./billing-service

  fraud:
    build: ./fraud-service

